### ISSUE TITLE
AlexNet ValueError: Negative dimension size caused by subtracting 16 from 1

### ISSUE THREAD

**Issue by tracek** [bapalto/birdsong-keras#3]
Hi,

When running trainModel.py, I get the following error:

```
model-AlexNet.py:45: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(kernel_initializer="glorot_normal", activation="relu", input_shape=(1, 200, 3..., padding="valid", strides=(6, 6), filters=96, kernel_size=(16, 16))`
  subsample=(6, 6)
Traceback (most recent call last):
  File "model-AlexNet.py", line 45, in <module>
    subsample=(6, 6)
  File "/anaconda/lib/python2.7/site-packages/keras/models.py", line 430, in add
    layer(x)
  File "/anaconda/lib/python2.7/site-packages/keras/engine/topology.py", line 578, in __call__
    output = self.call(inputs, **kwargs)
  File "/anaconda/lib/python2.7/site-packages/keras/layers/convolutional.py", line 164, in call
    dilation_rate=self.dilation_rate)
  File "/anaconda/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 2893, in conv2d
    data_format='NHWC')
  File "/anaconda/lib/python2.7/site-packages/tensorflow/python/ops/nn_ops.py", line 639, in convolution
    op=op)
  File "/anaconda/lib/python2.7/site-packages/tensorflow/python/ops/nn_ops.py", line 308, in with_space_to_batch
    return op(input, num_spatial_dims, padding)
  File "/anaconda/lib/python2.7/site-packages/tensorflow/python/ops/nn_ops.py", line 631, in op
    name=name)
  File "/anaconda/lib/python2.7/site-packages/tensorflow/python/ops/nn_ops.py", line 129, in _non_atrous_convolution
    name=name)
  File "/anaconda/lib/python2.7/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 396, in conv2d
    data_format=data_format, name=name)
  File "/anaconda/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "/anaconda/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2329, in create_op
    set_shapes_for_outputs(ret)
  File "/anaconda/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1717, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "/anaconda/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1667, in call_with_requiring
    return call_cpp_shape_fn(op, require_shape_fn=True)
  File "/anaconda/lib/python2.7/site-packages/tensorflow/python/framework/common_shapes.py", line 610, in call_cpp_shape_fn
    debug_python_shape_fn, require_shape_fn)
  File "/anaconda/lib/python2.7/site-packages/tensorflow/python/framework/common_shapes.py", line 676, in _call_cpp_shape_fn_impl
    raise ValueError(err.message)
ValueError: Negative dimension size caused by subtracting 16 from 1 for 'conv2d_1/convolution' (op: 'Conv2D') with input shapes: [?,1,200,310], [16,16,310,96].
```

Perhaps it's a change from Keras 1 to 2, but it seems that the `input_shape' should be in form of (200,310,1), the latter being depth, rather (1,200,310).

**Comment by matbenyo** [comment]
I'm not sure, but take care to the backend. The authors suggest using theano dimension ordering, as you can see in the readme file:
"image_dim_ordering": "th",

**Comment by tracek** [comment]
In Keras 2, "image_dim_ordering" is deprecated, replaced by "image_data_format". The latter by default is set to "channels_last". You can set `"image_dim_ordering": "th"`, but it won't do you any good. I would suggest an edit in the readme that in Keras 2 user should change the "image_data_format" setting to "channels_first".

**Comment by bapalto** [comment]
Thank you for the clarifications. I updated the readme.
